#' @title Pull results from WHAM
#' @description Pull out results required for MT report writing from a WHAM model
#' 
#' @param model A fitted WHAM model object, no default.
#' @param multiWHAM A boolean, if TRUE, assumes that the model is generated by multi-WHAM and includes additional indexing for region/stock as well as any differences in labels. Default = FALSE.
#' 
#' @return A list containing the following
#' \itemize{
#'   \item{brps - A table of BRP estimates with 95% CI for F, SSB and MSY proxies}
#'   \item{NAA - A table of NAA}
#'   \item{FAA - A table of FAA}
#'   \item{Mohns_rho - A list of Mohn's rho values for F, SSB, and NAA}
#'   \item{F.yr - A table containing a time series of F estimates and CVs}
#'   \item{F.yr_adj - F.yr table with Mohn's rho adjustments}
#'   \item{SSB.yr - A table containing a time series of SSB estimates and CVs}
#'   \item{SSB.yr_adj - SSB.yr table with Mohn's rho adjustments}
#'   \item{Rect.yr - A table containing a time series of Recruitment and CVs}
#'   \item{Rect.yr_adj - Rect.yr table with Mohn's rho adjustments}
#'   \item{termyr.ests.cis - A table of terminal year estimates of F, SSB, and Recruitment with 95% and 90% CIs}
#' }


#model <- readRDS("C:/Users/amanda.hart/Cod_GBK/MT/Cod_GB_MT_2024/Bridge_runs/9_bridge_reviseCV_NEFSC/9_bridge_model.rds")


pullResults_WHAM <- function(model = NULL,
                             multiWHAM = FALSE){
  ## Storage for returned list #####
  return_list <- NULL
  
  ## Basic wham #####
  
  # Pull model estimates
  model_est <- as.list(model$sdrep, what = "Est", report = TRUE)
  model_sd <- as.list(model$sdrep, what = "Std", report = TRUE)
  
  # Reference points
  model_Fproxy <- model_est$log_FXSPR_static %>% exp() %>% c(est = ., lo = NA, hi = NA) 
  
  model_SSBproxy <- data.frame(logSSBproxy = model_est$log_SSB_FXSPR_static, logSSBproxy_sd = model_sd$log_SSB_FXSPR_static) %>%
    mutate(est = exp(logSSBproxy),
           lo = exp(logSSBproxy - qnorm(0.975)*logSSBproxy_sd),
           hi = exp(logSSBproxy + qnorm(0.975)*logSSBproxy_sd)) %>% distinct() # Remove duplicates introduced by lines 31-32
  
  model_MSYproxy <- data.frame(logMSYproxy = model_est$log_Y_FXSPR_static, logMSYproxy_sd = model_sd$log_Y_FXSPR_static) %>%
    mutate(est = exp(logMSYproxy),
           lo = exp(logMSYproxy - qnorm(0.975)*logMSYproxy_sd),
           hi = exp(logMSYproxy + qnorm(0.975)*logMSYproxy_sd)) %>% distinct() # Remove duplicates introduced by lines 31-32
  
  brps <- bind_rows('Fproxy' = model_Fproxy, 'SSBproxy' = model_SSBproxy, 'MSYproxy' = model_MSYproxy, .id="BRP") %>% select(BRP, est, lo, hi)
  
  return_list$brps <- brps
  
  # At-age information
  if(multiWHAM == TRUE){
    NAA <- cbind(YEAR = model$years, model$rep$NAA[1,,,]) # Should check that this works for BSB since this additional indexing present in multi-wham only
    colnames(NAA) <- c("YEAR", paste0("AGE", model$ages.lab))
  } else{
    NAA <- cbind(YEAR = model$years, model$rep$NAA)
    colnames(NAA) <- c("YEAR", paste0("AGE", model$ages.lab))
  }
  return_list$NAA <- NAA
  
  if(multiWHAM == TRUE){
    FAA <- cbind(YEAR = model$years, exp(model$rep$log_FAA_tot))
    colnames(FAA) <- c("YEAR", paste0("AGE", model$ages.lab))
  } else{
    FAA <- cbind(YEAR = model$years, model$rep$FAA_tot)
    colnames(FAA) <- c("YEAR", paste0("AGE", model$ages.lab))
  }
  return_list$FAA <- FAA
  
  # Mohn's rho
  Mohns_rho <- mohns_rho(model)
  names(Mohns_rho)[names(Mohns_rho)=='Fbar'] <- 'F'
  names(Mohns_rho)[names(Mohns_rho)=='R'] <- 'Rect'
  return_list$Mohns_rho <- Mohns_rho
  
  # Annual F
  if(multiWHAM == TRUE){
    F.yr <- calc.uncertainty(log.est = model_est$log_F_tot, log.se = model_sd$log_F_tot) %>% mutate(YEAR = model$years, .before = "est") %>%
      mutate(relF = est/model_Fproxy["est"]) %>%
      calc.rho.adj.ests(., rho = Mohns_rho$F) %>% # !!! May need to check if should be Fbar or ["Fbar"]
      mutate(relF.adj = est.adj/model_Fproxy["est"])
  } else{
    F.yr <- calc.uncertainty(log.est = model_est$log_F, log.se = model_sd$log_F) %>% mutate(YEAR = model$years, .before = "est") %>%
      mutate(relF = est/model_Fproxy["est"]) %>%
      calc.rho.adj.ests(., rho = Mohns_rho["F"]) %>%
      mutate(relF.adj = est.adj/model_Fproxy["est"])
  }
  
  return_list$F.yr <- F.yr %>% select(Year = YEAR, F = est, F.CV = CV)
  return_list$F.yr_adj <- F.yr
  
  # Annual SSB
  SSB.yr <- calc.uncertainty(log.est = model_est$log_SSB, log.se = model_sd$log_SSB) %>% mutate(YEAR = model$years, .before = "est") %>%
    mutate(relSSB = est/model_SSBproxy["est"]) %>% #!!! confirm this is working as desired
    calc.rho.adj.ests(., rho = Mohns_rho["SSB"]) %>%  # !!! confirm that ["SSB"] syntax works for multi-wham
    mutate(relSSB.adj= est.adj/model_SSBproxy["est"])
  
  return_list$SSB.yr <- SSB.yr %>% select(Year = YEAR, SSB = est, SSB.CV = CV)
  return_list$SSB.yr_adj <- SSB.yr
  
  # Recruitment
  if(multiWHAM == TRUE){
    Rect.yr <- calc.uncertainty(log.est = model_est$log_NAA_rep[1,,,1], log.se = model_sd$log_NAA_rep[1,,,1]) %>% mutate(YEAR = model$years, .before = "est") %>%
      calc.rho.adj.ests(., rho = Mohns_rho$naa[1]) # !!! confirm naa indexing for mohn's rho works across multi-wham options
  } else{
    Rect.yr <- calc.uncertainty(log.est = model_est$log_NAA_rep[,1], log.se = model_sd$log_NAA_rep[,1]) %>% mutate(YEAR = model$years, .before = "est") %>%
      calc.rho.adj.ests(., rho = Mohns_rho["Rect"]) 
  }
  
  return_list$Rect.yr <- Rect.yr %>% select(Year = YEAR, Rect = est, Rect.CV = CV)
  return_list$Rect.yr_adj <- Rect.yr
  
  # Condense terminal year estimates with CIs
  model.lyr = tail(model$years, n=1)
  
  F = filter(F.yr, YEAR == model.lyr) %>% rename(BRP.ratio = relF, BRP.ratio.adj = relF.adj)
  # names(F)[7]  = "BRP.ratio"                 # Set up F
  # names(F)[11] = "BRP.ratio.adj"
  
  SSB = filter(SSB.yr, YEAR == model.lyr) %>% rename(BRP.ratio = relSSB, BRP.ratio.adj = relSSB.adj)
  # names(SSB)[7]  = "BRP.ratio"               # Set up SSB
  # names(SSB)[11] = "BRP.ratio.adj"
  
  # Pull terminal estimates 
  if(model$input$data$n_fleets > 1){ # If multiple fleets
    for (i in 1:ncol(F)) {
      F[,i] = as.numeric(F[,i])
    }
    for (i in 1:ncol(SSB)) {
      SSB[,i] = as.numeric(SSB[,i])            # Negating Single-WHAM issues of class
    }
    
    F_fleet <- NULL
    for(ifleet in 1:model$input$data$n_fleets){
      F_fleet[[ifleet]] <-  F[grep(paste0(".", ifleet), colnames(F))]
      colnames(F_fleet[[ifleet]]) <- c("est", "CV", "lo_90", "hi_90", "lo_95", "hi_95", "BRP.ratio", "est.adj", "lo.adj", " hi.adj", " BRP.ratio.adj")
    }
    F_fleet = F_fleet %>% bind_rows()
    
    termyr.ests.cis <- bind_rows(
      F = F_fleet,
      SSB=SSB,
      .id = "Parameter") %>%
      bind_rows(., filter(Rect.yr, YEAR == model.lyr) %>% mutate(Parameter = "Rect")) %>%
      select(Parameter, est, CV, lo_90, hi_90, BRP.ratio, est.adj, lo.adj, hi.adj, BRP.ratio.adj) 
    termyr.ests.cis$Parameter[1:model$input$data$n_fleets] = "F"
    termyr.ests.cis$Parameter[model$input$data$n_fleets+1] = "SSB"
    
    
  } else{ # If only one fleet
    for (i in 1:ncol(F)) {
      F[,i] = as.numeric(F[,i])
      SSB[,i] = as.numeric(SSB[,i])            # Negating Single-WHAM issues of class
    }
    
    termyr.ests.cis <- bind_rows(
      F=F,
      SSB=SSB,
      .id = "Parameter") %>%
      bind_rows(., filter(Rect.yr, YEAR == model.lyr) %>% mutate(Parameter = "Rect")) %>%
      select(Parameter, est, CV, lo_90, hi_90, BRP.ratio, est.adj, lo.adj, hi.adj, BRP.ratio.adj) 
    termyr.ests.cis$Parameter[1] = "F"
    termyr.ests.cis$Parameter[2] = "SSB"
  }
  
  return_list$termyr.ests.cis <- termyr.ests.cis
  
  # Return
  return(return_list)
}






