---
title: "CAMS discard tripping hazard"
author: "Chris Legault"
date: May 27, 2025
format: 
  html:
    page-layout: full
    embed-resources: true  
highlight-style: zenburn
---

## BLUF

Summarizing CAMS discards from CAMS_DISCARD_ALL_YEARS using variables in CAMS_DISCARD_STRATA can lead to inadvertent loss of discards due to the observed trips having a null strata_used_desc value.

## Details

CAMS 2.0 reduced the size of CAMS_DISCARD_ALL_YEARS by removing a number of columns and creating a new table called CAMS_DISCARD_STRATA to serve as a look up table to decipher the strata_used_desc column. The strata_used_desc column is the primary key linking the CAMS_DISCARD_ALL_YEARS and CAMS_DISCARD_STRATA tables. However, the null values for observed trips means that the additional information from CAMS_DISCARD_STRATA cannot be used and the information must be found another way. 

This problem can be seen in the "Simple Black Sea Bass example - bad" code and results shown below. Joining CAMS_DISCARD_ALL_YEARS and CAMS_DISCARD_STRATA using strata_used_desc when grouping by species_stock and discard_source results in the expected values for the North and South groups of black sea bass and discard_sources of G, GM, I, and T, but the observed trips (discard_source = 'O') do not get assigned to either the North or South group, instead they appear as a null group. While this is not a large portion of the total discards, it could be a problem if this approach was used to determine the North and South discards and the null area was ignored. 

One way to address this problem can be seen in the "Simple Black Sea Bass example - good" code and results shown below. The strategy is to separately calculated discards for discard_source = 'O' using other tables to define the required species_stock. In this case, cams_subtrip is used to identify the area where the subtrip occurred and cams_cfg_statarea_stock is used to assign the area for each subtrip to a species_stock. The results of this portion of the code are then combined with the standard approach that is applied to all discard sources other than observed using the UNION function (similar to rbind in R). The UNION function requires the columns of the two tables being joined to have the same names and types, just like rbind in R. The results for this approach now show all the Black Sea Bass discards correctly assigned to the North and South area by discard source.

In the simple example, the incorrect assignment was easy to notice due to the small number of records returned by the bad code. The null values will not always be as easily noticed when a more detailed breakdown is requested. Special thanks to Emily Liljestrand for bringing this problem to my attention and leading to this document.

The "Complex Black Sea Bass example - bad" provides a demonstration of how challenging it can be to even notice that the null values are present due to the large number of records returned. In this example, the Black Sea Bass discards are desired by species_stock, cams_gear_group, and month. Ignoring the lack of ability to match on the null records for discard_source = 'O' results in 366 records with 92.4 metric tons of discards in species_stock = null. If this relatively large number of records was not closely examined, the null area discards could easily be missed. Similarly, if only one of the areas was desired as the result, say the North area, in the call, then the null areas would not be included and the discard values would be incorrect. Note that even though discard_source is not one of the desired breakdowns, the inability to match discard_source = 'O' still causes a problem. There are 92.4 mt of discards with null area and null cams_gear_group due to the matching process. Since month is extracted from the date_trip found in the CAMS_DISCARD_ALL_YEARS, it can be summed correctly because even the discard_source = 'O' records in this table have the date_trip so no joining to CAMS_DISCARD_STRATA is needed for this variable.

The approach to solve the problem is the same, but the SQL code needs to be a bit more complex because multiple tables are now needed to derive the desired outputs, as seen in the "Complex Black Sea Bass example - good" code below. Grabbing the results of both the good and bad examples and summing the discard mt demonstrates that the totals for both approaches are the same, it is just that the observed trips are correctly apportioned in the good example. This complex example also demonstrates the ability to convert discard pounds to metric tons and estimate the coefficient of variance of the discards. These additional steps are nice to have and demonstrate that SQL code can be built slowly one step at a time to result in complex results, but that checking should always be done on results to ensure that records are not lost and that Cartesian products are not formed.

## Simple Black Sea Bass example - bad

```sql
select a.itis_tsn
  , a.year
  , b.species_stock
  , a.discard_source
  , sum(a.cams_discard) as discard_lb
  from cams_discard_all_years a
  left join cams_discard_strata b
  on a.strata_used_desc = b.strata_used_desc
  where a.itis_tsn = '167687' 
  and a.year = 2024 
  group by a.itis_tsn, a.year, b.species_stock, a.discard_source
  order by a.year, b.species_stock, a.discard_source;
/*
167687	2024	NORTH	G	193207.9
167687	2024	NORTH	GM	52159.46
167687	2024	NORTH	I	2037872.39
167687	2024	NORTH	T	1.34
167687	2024	SOUTH	G	7208.62
167687	2024	SOUTH	GM	165260.25
167687	2024	SOUTH	I	73731.52
167687	2024	SOUTH	T	2054.49
167687	2024	(null)	O	130914.58
*/

```

## Simple Black Sea Bass example - good

```sql
with dso as
(select a.camsid, a.subtrip, a.itis_tsn, a.year, a.discard_source, b.area, c.area_name as species_stock, a.cams_discard 
 from cams_discard_all_years a
 left join cams_subtrip b
 on a.camsid = b.camsid and a.subtrip=b.subtrip
 left join cams_cfg_statarea_stock c
 on b.area = c.area and a.itis_tsn = c.itis_tsn
  where a.itis_tsn = '167687' 
  and a.year = 2024 
  and a.discard_source = 'O')
  select itis_tsn
  , year
  , species_stock
  , discard_source
  , sum(cams_discard) as discard_lb
  from dso
  group by itis_tsn, year, species_stock, discard_source

union

select a.itis_tsn
  , a.year
  , b.species_stock
  , a.discard_source
  , sum(a.cams_discard) as discard_lb
  from cams_discard_all_years a
  left join cams_discard_strata b
  on a.strata_used_desc = b.strata_used_desc
  where a.itis_tsn = '167687' 
  and a.year = 2024 
  and a.discard_source <> 'O'
  group by a.itis_tsn, a.year, b.species_stock, a.discard_source
  
  order by year, species_stock, discard_source;
-- success!
/*
167687	2024	NORTH	G	193207.9
167687	2024	NORTH	GM	52159.46
167687	2024	NORTH	I	2037872.39
167687	2024	NORTH	O	126550.42
167687	2024	NORTH	T	1.34
167687	2024	SOUTH	G	7208.62
167687	2024	SOUTH	GM	165260.25
167687	2024	SOUTH	I	73731.52
167687	2024	SOUTH	O	4364.16
167687	2024	SOUTH	T	2054.49
*/

```

## Complex Black Sea Bass example - bad

```sql
 select a.itis_tsn
  , a.year
  , b.species_stock
  , b.cams_gear_group
  , extract(month from a.date_trip) as month
  , sum(a.cams_discard) discard_lb
  , sum(a.cams_discard_variance) variance_lb
  , sum(a.subtrip_kall) kall_lb 
  , count(*) as n
  , round(sum(a.cams_discard)*0.000453592370, 1) as discard_mt
  , case when sum(a.cams_discard) = 0 then 0
     else round(sqrt(sum(a.cams_discard_variance))/sum(a.cams_discard), 4) end as discard_cv
from cams_discard_all_years a
left join cams_discard_strata b
on a.strata_used_desc = b.strata_used_desc
 where a.itis_tsn='167687' 
 and a.year = 2019
 group by a.itis_tsn, a.year, b.species_stock, b.cams_gear_group, extract(month from a.date_trip)
 order by species_stock, discard_mt desc;
 -- 366 records with 92.4 metric tons of discards in species_stock = null and cams_gear_group = null

```

## Complex Black Sea Bass example - good

```sql
with dso as
(select a.camsid, a.subtrip, a.itis_tsn, a.year, a.discard_source, b.area, c.area_name as species_stock, 
        b.negear, d.secgear_mapped, e.cams_gear_group, extract(month from a.date_trip) as month, 
        a.cams_discard, a.cams_discard_variance, a.subtrip_kall 
 from cams_discard_all_years a
 left join cams_subtrip b
 on a.camsid = b.camsid and a.subtrip=b.subtrip
 left join cams_cfg_statarea_stock c
 on b.area = c.area and a.itis_tsn = c.itis_tsn
 left join cams_cfg_negear d
 on b.negear = d.negear
 left join cams_cfg_gearcode_strata e
 on a.itis_tsn = e.itis_tsn and d.secgear_mapped = e.secgear_mapped
 
  where a.itis_tsn = '167687' 
  and a.year = 2019
  and a.discard_source = 'O')
  select itis_tsn
  , year
  , species_stock
  , cams_gear_group
  , month
  , sum(cams_discard) as discard_lb
  , sum(cams_discard_variance) variance_lb
  , sum(subtrip_kall) kall_lb 
  , count(*) as n
  , round(sum(cams_discard)*0.000453592370, 1) as discard_mt
  , case when sum(cams_discard) = 0 then 0
     else round(sqrt(sum(cams_discard_variance))/sum(cams_discard), 4) end as discard_cv
  from dso
  group by itis_tsn, year, species_stock, cams_gear_group, month

union

select a.itis_tsn
  , a.year
  , b.species_stock
  , b.cams_gear_group
  , extract(month from a.date_trip) as month
  , sum(a.cams_discard) discard_lb
  , sum(a.cams_discard_variance) variance_lb
  , sum(a.subtrip_kall) kall_lb 
  , count(*) as n
  , round(sum(a.cams_discard)*0.000453592370, 1) as discard_mt
  , case when sum(a.cams_discard) = 0 then 0
     else round(sqrt(sum(a.cams_discard_variance))/sum(a.cams_discard), 4) end as discard_cv
from cams_discard_all_years a
left join cams_discard_strata b
on a.strata_used_desc = b.strata_used_desc
 where a.itis_tsn='167687' 
 and a.year = 2019
 and a.discard_source <> 'O'
 group by a.itis_tsn, a.year, b.species_stock, b.cams_gear_group, extract(month from a.date_trip)

 order by species_stock, discard_mt desc;
 -- 552 records with no species_stock = null or cams_gear_group = null results
```
